#pragma once
// Auto-generated by scripts/generate_apitems.py
// Do not edit manually - regenerate by modifying src/okami-apclient/apitems.yml

#include <cstdint>
#include <string>
#include <unordered_map>

namespace apitems
{

// Item handler types
enum class ItemHandlerType
{
    Brush,            // Regular brush technique
    ProgressiveBrush, // Power Slash / Cherry Bomb with upgrades
    Inventory,        // Direct inventory item
    EventFlags,       // Sets game state flags
    Progressive,      // Progressive weapons
};

// Flag information for event_flags items
struct FlagInfo
{
    const char *accessor_name; // Name of accessor in apgame namespace
    unsigned int bit;          // Bit index to set
};

// Item definition structure
struct APItemDef
{
    int id;
    const char *name;
    ItemHandlerType type;

    // Type-specific data
    union
    {
        // For Brush type
        struct
        {
            int brush_index;
        } brush;

        // For ProgressiveBrush type
        struct
        {
            int brush_index;
            const unsigned int *upgrade_bits;
            size_t upgrade_count;
        } progressive_brush;

        // For Inventory type
        struct
        {
            int item_id;
        } inventory;

        // For EventFlags type
        struct
        {
            const FlagInfo *flags;
            size_t flag_count;
        } event;

        // For Progressive type
        struct
        {
            const int *stages;
            size_t stage_count;
        } progressive;
    };
};

// Global item registry
extern const std::unordered_map<int, const APItemDef *> item_registry;

// Lookup item by ID
const APItemDef *findItem(int id);

} // namespace apitems
