# Auto-generated by generate_sources.cmake
set(okami-apclient_SOURCES
  ${CMAKE_CURRENT_SOURCE_DIR}/apitems_generated.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/aplocationmonitor.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/archipelagosocket.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/gamestate_accessors.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/item_handlers.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/loginwindow.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/okami-apclient.cpp
)
