#pragma once

namespace okami
{
namespace BestiaryTome
{
enum Enum
{
    GreenImp,
    RedImp,
    YellowImp,
    BlueImp,
    BlackImp,
    HeadlessGuardian,
    BellGuardian,
    HaloGuardian,
    ExecutionerGuardian,
    Namahage,
    BladeNamahage,
    BucketNamahage,
    UmbrellaNamahage,
    CannonNamahage,
    ClaySoldier,
    ClaySamurai,
    ClayDrummer,
    ClayFlyer,
    ClayShogun,
    BudOgre,
    Chimera,
    IglooTurtle,
    DeadFish,
    CrowTengu,
    Ubume,
    FireEye,
    IceMouth,
    ThunderEar,
    EarthNose,
    FireDoomMirror,
    IceDoomMirror,
    ThunderDoomMirror,
    WindDoomMirror,
    Poltergeist,
    Ichiro,
    Jiro,
    Saburo,
    BlueCyclops,
    GreatTengu,
    CrimsonHelm,
    RedOgre,
    BlueOgre,
    BullCharger,
    SpiderQueen,
    BanditSpider,
    Orochi,
    TrueOrochi,
    Waka,
    Waka2,
    Blight,
    EvilRao,
    Oki,
    Nagi,
    Dogu,
    Ninetails,
    CanineWarriorChu,
    CanineWarriorJin,
    CanineWarriorGi,
    CanineWarriorTei,
    CanineWarriorChi,
    CanineWarriorKo,
    CanineWarriorRei,
    CanineWarriorShin,
    TubeFox,
    GoldenDemonLechku,
    SilverDemonNechku,
    YamiRed,
    YamiGreen,
    YamiBlue,
    YamiYellow,
    YamiHand,
    NUM_BESTIARY_ENTRIES
};

const char *GetName(unsigned index);
} // namespace BestiaryTome
} // namespace okami
