# generate_sources.cmake — Run with: cmake -P generate_sources.cmake -DSOURCE_DIR=...
# This script generates src/client/sources.cmake *only if* the contents have changed.

if(NOT DEFINED SOURCE_DIR)
    message(FATAL_ERROR "SOURCE_DIR not defined")
endif()

set(CLIENT_DIR "${SOURCE_DIR}/src/client")
set(OUTPUT_FILE "${CLIENT_DIR}/sources.cmake")
set(TEMP_FILE "${OUTPUT_FILE}.tmp")

# Find all .cpp files relative to SOURCE_DIR
file(GLOB_RECURSE CLIENT_CPP_FILES
    RELATIVE "${SOURCE_DIR}"
    "${CLIENT_DIR}/*.cpp"
)

# Create the temporary version of the output
file(WRITE "${TEMP_FILE}" "# Auto-generated by generate_sources.cmake\n")
file(APPEND "${TEMP_FILE}" "set(CLIENT_SOURCES\n")

foreach(source_file IN LISTS CLIENT_CPP_FILES)
    file(APPEND "${TEMP_FILE}" "  \${CMAKE_CURRENT_SOURCE_DIR}/${source_file}\n")
endforeach()

file(APPEND "${TEMP_FILE}" ")\n")

# Compare with existing version
set(NEEDS_UPDATE TRUE)
if(EXISTS "${OUTPUT_FILE}")
    file(READ "${OUTPUT_FILE}" EXISTING_CONTENT)
    file(READ "${TEMP_FILE}" NEW_CONTENT)
    if(EXISTING_CONTENT STREQUAL NEW_CONTENT)
        set(NEEDS_UPDATE FALSE)
        file(REMOVE "${TEMP_FILE}")
    endif()
endif()

# Replace only if changed
if(NEEDS_UPDATE)
    file(RENAME "${TEMP_FILE}" "${OUTPUT_FILE}")
    message(STATUS "Updated: ${OUTPUT_FILE}")
else()
    message(STATUS "No change: ${OUTPUT_FILE}")
endif()
