# Auto-generated by generate_sources.cmake
set(client_SOURCES
  ${CMAKE_CURRENT_SOURCE_DIR}/src/client/aplocationmonitor.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/src/client/archipelagosocket.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/src/client/checks.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/src/client/console.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/src/client/devdatafinder.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/src/client/devtools.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/src/client/dllmain.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/src/client/gamehooks.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/src/client/gui.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/src/client/logger.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/src/client/loginwindow.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/src/client/receive.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/src/client/shopdef.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/src/client/shops.cpp
)
