name: Build

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build-windows:
    name: Build on ${{ github.ref_name }}
    runs-on: windows-latest

    defaults:
      run:
        shell: pwsh
        working-directory: ${{ github.workspace }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: List Presets (debug)
        run: cmake --list-presets

      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Configure CMake Release
        if: github.ref_name == 'master' || github.event.pull_request.base.ref == 'master'
        run: cmake --preset x64-clang-release

      - name: Build Release
        if: github.ref_name == 'master' || github.event.pull_request.base.ref == 'master'
        run: cmake --build --preset x64-clang-release

      - name: Configure CMake Debug
        if: github.ref_name == 'develop' || github.event.pull_request.base.ref == 'develop'
        run: cmake --preset x64-clang-debug

      - name: Build Debug
        if: github.ref_name == 'develop' || github.event.pull_request.base.ref == 'develop'
        run: cmake --build --preset x64-clang-debug

      - name: Read Version
        id: get_version
        run: |
          $version = Get-Content out/build/x64-clang-release/version.txt
          echo "version=$version" >> $env:GITHUB_OUTPUT
      
      - name: Create staging layout
        run: |
          mkdir -p release/mods/apclient
          cp out/build/x64-release/okami-apclient.dll release/mods/apclient/
          cp out/build/x64-release/cacert.pem release/mods/apclient/
          cp out/build/x64-release/apclient-loader.dll release/mods/

      - name: Zip build
        run: |
          Compress-Archive -Path release/* -DestinationPath okami-apclient-${{ steps.get_version.outputs.version }}.zip

      - name: Conditionally Upload Artifacts
        if: github.ref_name == 'master' || github.event.pull_request.base.ref == 'master'
        uses: actions/upload-artifact@v4
        with:
          name: okami-apclient-${{ steps.get_version.outputs.version }}-package
          path: okami-apclient-${{ steps.get_version.outputs.version }}.zip
